### ISSUE TITLE
Apply default "darkula" theme for base IDE build.

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/adaptive-ide-base#6]

**Comment by Panthro** [comment]
Do you have any idea where we can set it for once and for all?

I have found that by adding the following properties on the idea.properties file at build time it starts as Darcula:

```
-Dswing.laf=com.intellij.ide.ui.laf.darcula.DarculaLaf
-Dswing.systemlaf=com.intellij.ide.ui.laf.darcula.DarculaLaf
```

But as soon as it loads the full IDE come backs to intellij default, even if I remove the whole config dir it still changes to the default.

No luck on setting it to Darcula effectively.
