### ISSUE TITLE
Tag @@product_state@@ not being replaced by build.

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/adaptive-ide-base#9]
![screen shot 2015-03-26 at 23 43 56](https://cloud.githubusercontent.com/assets/1463304/6858762/fd3bff82-d411-11e4-97ca-21830b1498cb.png)

**Comment by carloslozano** [comment]
I think this is probably the product channel "EA" "Beta", etc.

**Comment by Panthro** [comment]
fixed by 76e7ba43466bc17d0003e52a17bd68e67ca3579e
